version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - django-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - django-network

networks:
  django-network:
    driver: bridge
